# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComparatorStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessData = channel.unary_unary(
                '/comparator.Comparator/ProcessData',
                request_serializer=services__pb2.NumberList.SerializeToString,
                response_deserializer=services__pb2.Number.FromString,
                _registered_method=True)
        self.GetWordCount = channel.unary_unary(
                '/comparator.Comparator/GetWordCount',
                request_serializer=services__pb2.Text.SerializeToString,
                response_deserializer=services__pb2.WordCountResponse.FromString,
                _registered_method=True)
        self.GetMinMax = channel.unary_unary(
                '/comparator.Comparator/GetMinMax',
                request_serializer=services__pb2.NumberList.SerializeToString,
                response_deserializer=services__pb2.MinMaxResponse.FromString,
                _registered_method=True)
        self.GetSorted = channel.unary_unary(
                '/comparator.Comparator/GetSorted',
                request_serializer=services__pb2.NumberList.SerializeToString,
                response_deserializer=services__pb2.SortedResponse.FromString,
                _registered_method=True)
        self.GetPrimes = channel.unary_unary(
                '/comparator.Comparator/GetPrimes',
                request_serializer=services__pb2.NumberList.SerializeToString,
                response_deserializer=services__pb2.NumberList.FromString,
                _registered_method=True)


class ComparatorServicer(object):
    """The service definition.
    """

    def ProcessData(self, request, context):
        """1. MapReduce (simplified as ProcessData)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWordCount(self, request, context):
        """2. Word Count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMinMax(self, request, context):
        """3. Find Min/Max
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSorted(self, request, context):
        """4. Sort Numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimes(self, request, context):
        """5. List Primes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComparatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessData,
                    request_deserializer=services__pb2.NumberList.FromString,
                    response_serializer=services__pb2.Number.SerializeToString,
            ),
            'GetWordCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWordCount,
                    request_deserializer=services__pb2.Text.FromString,
                    response_serializer=services__pb2.WordCountResponse.SerializeToString,
            ),
            'GetMinMax': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinMax,
                    request_deserializer=services__pb2.NumberList.FromString,
                    response_serializer=services__pb2.MinMaxResponse.SerializeToString,
            ),
            'GetSorted': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSorted,
                    request_deserializer=services__pb2.NumberList.FromString,
                    response_serializer=services__pb2.SortedResponse.SerializeToString,
            ),
            'GetPrimes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimes,
                    request_deserializer=services__pb2.NumberList.FromString,
                    response_serializer=services__pb2.NumberList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comparator.Comparator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('comparator.Comparator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Comparator(object):
    """The service definition.
    """

    @staticmethod
    def ProcessData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comparator.Comparator/ProcessData',
            services__pb2.NumberList.SerializeToString,
            services__pb2.Number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWordCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comparator.Comparator/GetWordCount',
            services__pb2.Text.SerializeToString,
            services__pb2.WordCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMinMax(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comparator.Comparator/GetMinMax',
            services__pb2.NumberList.SerializeToString,
            services__pb2.MinMaxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSorted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comparator.Comparator/GetSorted',
            services__pb2.NumberList.SerializeToString,
            services__pb2.SortedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comparator.Comparator/GetPrimes',
            services__pb2.NumberList.SerializeToString,
            services__pb2.NumberList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
