# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\ncomparator\"\x1d\n\nNumberList\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"\x17\n\x04Text\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"}\n\x11WordCountResponse\x12\x39\n\x06\x63ounts\x18\x01 \x03(\x0b\x32).comparator.WordCountResponse.CountsEntry\x1a-\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"*\n\x0eMinMaxResponse\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\"7\n\x0eSortedResponse\x12\x11\n\tascending\x18\x01 \x03(\x05\x12\x12\n\ndescending\x18\x02 \x03(\x05\x32\xd1\x02\n\nComparator\x12;\n\x0bProcessData\x12\x16.comparator.NumberList\x1a\x12.comparator.Number\"\x00\x12\x41\n\x0cGetWordCount\x12\x10.comparator.Text\x1a\x1d.comparator.WordCountResponse\"\x00\x12\x41\n\tGetMinMax\x12\x16.comparator.NumberList\x1a\x1a.comparator.MinMaxResponse\"\x00\x12\x41\n\tGetSorted\x12\x16.comparator.NumberList\x1a\x1a.comparator.SortedResponse\"\x00\x12=\n\tGetPrimes\x12\x16.comparator.NumberList\x1a\x16.comparator.NumberList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNTRESPONSE_COUNTSENTRY']._loaded_options = None
  _globals['_WORDCOUNTRESPONSE_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_NUMBERLIST']._serialized_start=30
  _globals['_NUMBERLIST']._serialized_end=59
  _globals['_NUMBER']._serialized_start=61
  _globals['_NUMBER']._serialized_end=84
  _globals['_TEXT']._serialized_start=86
  _globals['_TEXT']._serialized_end=109
  _globals['_WORDCOUNTRESPONSE']._serialized_start=111
  _globals['_WORDCOUNTRESPONSE']._serialized_end=236
  _globals['_WORDCOUNTRESPONSE_COUNTSENTRY']._serialized_start=191
  _globals['_WORDCOUNTRESPONSE_COUNTSENTRY']._serialized_end=236
  _globals['_MINMAXRESPONSE']._serialized_start=238
  _globals['_MINMAXRESPONSE']._serialized_end=280
  _globals['_SORTEDRESPONSE']._serialized_start=282
  _globals['_SORTEDRESPONSE']._serialized_end=337
  _globals['_COMPARATOR']._serialized_start=340
  _globals['_COMPARATOR']._serialized_end=677
# @@protoc_insertion_point(module_scope)
